targets:
  $default:
    builders:
      bavard|fillable_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart
      bavard|pivot_generator:
        enabled: true
        generate_for:
          - lib/**/*.dart
          - test/**/*.dart

builders:
  fillable_generator:
    import: "package:bavard/src/generators/model_fillable_generator.dart"
    builder_factories: ["fillableGenerator"]
    # "fillable" is The `partId` argument passed to `SharedPartBuilder`
    build_extensions: {".dart": [".fillable.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]

  pivot_generator:
    import: "package:bavard/src/generators/pivot_generator.dart"
    builder_factories: ["pivotGenerator"]
    # "pivot" is The `partId` argument passed to `SharedPartBuilder`
    build_extensions: {".dart": [".pivot.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen:combining_builder"]
